apiVersion: v1
kind: Service
metadata:
  annotations:
    git-commit-hash: 78379dd82a991444ce18b8e61247761e13237cce
  labels:
    app: kubed
  name: kubed-operator
  namespace: kube-system
spec:
  ports:
  - name: api
    port: 8080
    targetPort: api
  - name: web
    port: 56790
    targetPort: web
  selector:
    app: kubed
